-- Cached partner-voice lines (Session 3): the Home presence line (one per
-- day) and the Logbook month caption (one per month). Generated by haiku in
-- edge functions with the caller's JWT — RLS scopes rows to the user.

create table if not exists public.daily_lines (
  user_id uuid not null references auth.users on delete cascade,
  day date not null,
  line text not null,
  created_at timestamptz default now(),
  primary key (user_id, day)
);

alter table public.daily_lines enable row level security;

create policy "daily_lines_select_own" on public.daily_lines
  for select using (user_id = (select auth.uid()));
create policy "daily_lines_insert_own" on public.daily_lines
  for insert with check (user_id = (select auth.uid()));

create table if not exists public.month_captions (
  user_id uuid not null references auth.users on delete cascade,
  month text not null, -- YYYY-MM
  caption text not null,
  created_at timestamptz default now(),
  primary key (user_id, month)
);

alter table public.month_captions enable row level security;

create policy "month_captions_select_own" on public.month_captions
  for select using (user_id = (select auth.uid()));
create policy "month_captions_insert_own" on public.month_captions
  for insert with check (user_id = (select auth.uid()));
